name: Death around The World
favicon: null
layout_spectrum: 0.07327965321019292
typography_spectrum: 0.23581586289219558
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6623142298776656
  lightness: 0.4734148853458464
  saturation: 0.655078844865784
  rhythmicContrast: 0.13380883913487196
purpose: []
